### ISSUE TITLE
starting angle change

### ISSUE THREAD

**Issue by cloudjanak** [sakrist/VBPieChart#11]
![ios simulator screen shot 08-jun-2015 5 11 27 pm](https://cloud.githubusercontent.com/assets/7457258/8034082/319255a4-0e02-11e5-9eec-ce985263e4e7.png)
![new](https://cloud.githubusercontent.com/assets/7457258/8034110/6a2790a0-0e02-11e5-9c56-98eb19e03ee7.png)
need initial look like 50% left 50% right instead on top bottom

**Comment by sakrist** [comment]
What the problem??
just set M_PI_2 to startAngle
