### ISSUE TITLE
Question:How to set corner radius to the pie piece?

### ISSUE THREAD

**Issue by inix** [sakrist/VBPieChart#13]
I have read the codes and docs of apple site,but I am still confuse which properties or method should I config to add corner radius effect to the pie piece like following picture,Could you help me ?

![corner](https://cloud.githubusercontent.com/assets/2264291/9160928/8d2dffe4-3f71-11e5-92d2-7888aa8f69c6.png)

Thanks

**Comment by sakrist** [comment]
Hi, sorry for late unswer. 
You need overwrite refreshPath in VBPiePiece.m

**Comment by inix** [comment]
OK Thanks
