### ISSUE TITLE
getting such output using VBPieChart ??

### ISSUE THREAD

**Issue by farazhaider88** [sakrist/VBPieChart#15]
Hi,
thank you for making such a cool library for pie charts. i came in a problem and i wanted to know if it can be done through this library. i need to draw this sort of pie chart, is it possible to make this using your library? thanks in advance

![wfbkc](https://cloud.githubusercontent.com/assets/1468654/10136613/cca28bea-660e-11e5-995e-7dc0147e9b8e.png)

**Comment by sakrist** [comment]
Yes, you can do it. But you will need customise a little.

**Comment by farazhaider88** [comment]
can you please let me know how can i do this.
