### ISSUE TITLE
Terminating since there is no system app

### ISSUE THREAD

**Issue by ReDetection** [sakrist/VBPieChart#17]
Hi there! I like the ease of this chart, but unfortunately I'm getting strange error on iPhone 6 (both simulator and the device) when I'm trying to scroll a UIScrollView/UITableView with the VBPieChart inside. I'm getting this weird `Terminating since there is no system app` error and can't find the cause. Did anyone seen this? Does anyone know how to fix it? 

#### Steps to repoduce
Run `pod try VBPieChart`, open the swift demo, and replace `ViewCotroller.swift` with this contents:
```swift
import UIKit

class ViewController: UIViewController {
    
    let scrollView = UIScrollView()
    let chart = VBPieChart()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.addSubview(scrollView)
        scrollView.frame = self.view.bounds
        scrollView.alwaysBounceVertical = true
        
        self.scrollView.addSubview(chart);
        
        chart.frame = CGRectMake(200, 50, 293, 256);
        chart.enableStrokeColor = true;
        chart.holeRadiusPrecent = 0.85;
        chart.enableInteractive = false
        chart.startAngle = Float(3*M_PI_2)
        
        let chartValues = map(1...42) {(_) in return ["value": 1, "color":UIColor(hexString:"dd191daa")] }
        chart.setChartValues(chartValues, animation:true)
        
    }
    
}
```

Then just grad the screen down and here the error. It does not fire any exception (I have a breakpoint for all exceptions enabled), it seems not like the memory overflow (profiler gives no hints also). Here is the gif also:

![no-system-app.gif](https://cloud.githubusercontent.com/assets/458005/11523993/c598f00c-98e8-11e5-9516-12e8724947d0.gif)

**Comment by sakrist** [comment]
what is the map? `let chartValues = map(1...42) {(_)`

I've tested with Version 7.1.1 (7B1005) on iPad and with Simulator. All works.

<img width="887" alt="screen shot 2015-12-02 at 11 05 13 a m" src="https://cloud.githubusercontent.com/assets/110199/11529524/91c0352c-98e5-11e5-87a5-774d60659afa.png">

**Comment by ReDetection** [comment]
`map` is a builtin swift1.2 (I'm using Xcode 6.4  6E35b) map function to map every element of the collection with the given closure to a new collection. I made the collection of same dicts repeated 42 times.

At the moment I can't say any steps to reproduce with Xcode 7.

**Comment by sakrist** [comment]
Works with new swift 2.0
