### ISSUE TITLE
How to set values in swift2.0

### ISSUE THREAD

**Issue by JanakLN** [sakrist/VBPieChart#18]
viewPieChart = [["name": "first", "value": 50.00, "color": UIColor.redColor()], ["name": "sec", "value": 50.00, "color": UIColor.blackColor()]]

**Comment by sakrist** [comment]
Is it question or what? Any background please.

**Comment by JanakLN** [comment]
Yes

**Comment by sakrist** [comment]
There is swift example in repository.

**Comment by JanakLN** [comment]
Please provide link for swift repo.

**Comment by sakrist** [comment]
https://github.com/sakrist/VBPieChart/blob/master/VBPieChart_swift/VBPieChart_swift/ViewController.swift
