### ISSUE TITLE
Can we create same sample for stacked Barchart with same animation? 

### ISSUE THREAD

**Issue by phadatareshankar** [sakrist/VBPieChart#20]
I want to use same animation in stacked bar chart to show rising animations for each stacked bar using CAShapeLayer.

Thanks,
Shankar

**Comment by sakrist** [comment]
I think there is possible, you need overwrite refreshPath in VBPiePiece.m, to generate another shapes for **stacked bar chart**.

**Comment by phadatareshankar** [comment]
For Bar chart i tried it to create another shape in refreshPath. but did not worked for me. Can you try from your end?
I liked your sample for piechart. same animation i want to use for stacked bar because each bar i want to fill with different color. you did it for pie with different section color in circular.
Appreciate your help.
Thanks,
Shankar

**Comment by sakrist** [comment]
Maybe this piece of code will give you thinking
```objc
- (CGMutablePathRef) refreshPath {    
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddRect(path, &_currentMatrix, CGRectMake(10, _startAngle*40, 50, _angle*40));
    CGPathCloseSubpath(path);
    return path;
}
```

**Comment by phadatareshankar** [comment]
Thanks Bro. Its working perfect. you saved me.

**Comment by sakrist** [comment]
Np. I actually did not realise that is possible, before you ask :+1:
