### ISSUE TITLE
Reset pieChart

### ISSUE THREAD

**Issue by JanakLN** [sakrist/VBPieChart#24]

**Comment by sakrist** [comment]
man, it looks like you trying assign to me your tasks...

**Comment by JanakLN** [comment]
Can you please provide us solution, we are learners.

**Comment by sakrist** [comment]
[_chart setChartValues:@[]];

**Comment by JanakLN** [comment]
viewPieChart.setChartValues([], animation: true)

App is crashing.

**Comment by sakrist** [comment]
viewPieChart.setChartValues([])

**Comment by JanakLN** [comment]
Sorry not working.

**Comment by sakrist** [comment]
have you tried with latest version?

**Comment by sakrist** [comment]
>>viewPieChart.setChartValues([], animation: true)
fixed in 0.4.1
