### ISSUE TITLE
Can i able to fill one section with dotted pattern.

### ISSUE THREAD

**Issue by phadatareshankar** [sakrist/VBPieChart#27]
Hi,
I want to fill one section with dotted pattern keeping its background color as it is. Just want to add dotted pattern. Is it possible?

Also attaching image what exactly i want to achieve.
![piechart_dotted_pattern](https://cloud.githubusercontent.com/assets/1539905/12524357/1ab41326-c122-11e5-8f89-371ad814b64d.png)

Appreciate your help on this!
Thanks,
Shankar

**Comment by sakrist** [comment]
Hi
Yes, pattern is possible even without changes to API.

UIColor *colorWithImagePattern = [UIColor colorWithPatternImage:[UIImage imageNamed:@"pattern.png"]];
and the use it as color for item in chartValues.

For gap you may need little change `refreshPath` in `VBPiePiece.m` file.

**Comment by sakrist** [comment]
Don't forget give a star for my repository :+1:

**Comment by sakrist** [comment]
Any more questions?

**Comment by phadatareshankar** [comment]
Hi,
I have one question, my pattern background color and dot color will be dynamic. how can i change if i use pattern image?
I tried one solution to change background color of image but not able to change dot color from image.

I already given stars and likes to your repository. 
Thanks,
Shankar

**Comment by sakrist** [comment]
sorry, did not got you.

**Comment by phadatareshankar** [comment]
Hi,
Your pattern solutions worked for me. Thanks a lot for your help!. 

Thanks,
Shankar
