### ISSUE TITLE
VBPieChart not add on UIView objective c

### ISSUE THREAD

**Issue by ammadPaki** [sakrist/VBPieChart#29]
hi,
I am creating a uiview in nib and setting uiview parent class 'vbpiechart' and set all  the thing copy from tutorial but the chart doesn't appear, and when i add chart to self.view it works fine, why this behavior.

**Comment by sakrist** [comment]
it does not work with nib files, yet

**Comment by sakrist** [comment]
Implemented

**Comment by sakrist** [comment]
Example of editing in xib
<img width="611" alt="screen shot 2017-05-12 at 10 01 24" src="https://cloud.githubusercontent.com/assets/110199/26146430/107ffb0e-3ae8-11e7-9f27-c0a9a87250b1.png">
