### ISSUE TITLE
Feature Request: Text Labels on pie pieces.

### ISSUE THREAD

**Issue by Voley** [sakrist/VBPieChart#3]
I have tried to manually add this feature to your library, I used CATextLayer - and it was somewhat successful. Everything works great until I need to animate movement. How do I sync movement of text layer with pie piece?
Here is the code of my improved version of your pie piece:
https://gist.github.com/Voley/c84453b9d88ad5b20672

**Comment by sakrist** [comment]
Need take math from here https://jsfiddle.net/sakrist/8r8z3kff/
