### ISSUE TITLE
Highlight slice piece programmatically 

### ISSUE THREAD

**Issue by anfriis** [sakrist/VBPieChart#30]
I would like to be able to highlight the largest slice piece programmatically like it can be done when the user taps a piece. It would of course be best to make a general highlightSlice method with an index parameter so all pieces can be highlighted.

I have tried to fork the project, and added the following code.

```
// Finds the largest piece in the chart and changes its accent
- (void) highlightLargestPiece {
    VBPiePiece *largestPiece = nil;

    for (VBPiePiece *piece in _piecesArray) {
        if (largestPiece == nil || (largestPiece.data.value.doubleValue < piece.data.value.doubleValue)) {
            largestPiece = piece;
        }
    }

    if (largestPiece != nil) {
        [self togglePieceAccent:largestPiece];
    }
}

- (void) togglePieceAccent:(VBPiePiece *)piece {
    if (piece.accentPrecent < FLT_EPSILON) {
        [piece animateToAccent:_maxAccentPrecent];
    } else {
        [piece animateToAccent:0];
    }

```

Then i made the highlightLargestPiece public, but i somehow cannot call it from Swift - i get an unrecognized selector error, even though the code compiles.
The compiler is somehow recognizing the new method, but during runtime it apparently doesn't exist. 

Does someone know what is wrong?

**Comment by Anders123fr** [comment]
Anyone?

**Comment by sakrist** [comment]
this is strange, will check later

**Comment by sakrist** [comment]
I think this is outdated.
