### ISSUE TITLE
How to start drawing pie chart from 12 o Clock marker, right now its starting drawing from 3 o clock marker

### ISSUE THREAD

**Issue by phadatareshankar** [sakrist/VBPieChart#33]
What angel need to be change to start drawing from 12 o clock marker of circular clock?

**Comment by sakrist** [comment]
chart.startAngle

**Comment by phadatareshankar** [comment]
I tried setting startAngel to 360/90/180/270, but its not starting drawing from 12 o clock marker, its starts from other wrong positions. Could you tell me what exact angel i need to set?

**Comment by sakrist** [comment]
I think it's M_PI+M_PI_2, and it was default in example.

**Comment by phadatareshankar** [comment]
Thanks, Now its working.
