### ISSUE TITLE
ViewController退出闪退问题

### ISSUE THREAD

**Issue by FantasyWind2016** [sakrist/VBPieChart#36]
初始化方法：
- (id) init {
    self = [super init];
    [self configure];
    return self;
}
应该改为：
- (id) init {
    self = [self initWithFrame:CGRectZero];
//    [self configure];
    return self;
}
否则，使用[[VBPieChart alloc] init]代码进行初始化时，[self configure]方法可能会调用两次，导致对象释放时出现异常而闪退。

**Comment by sakrist** [comment]
Hi
I've translated with google translate, but not sure if I understood correctly. 
You saying that initialisation needs to be changed in order to avoid double configuration, is it right?

**Comment by sakrist** [comment]
I think it's been fixed with [6cd08b](https://github.com/sakrist/VBPieChart/commit/6cd08b345e93f041309210741a0bf35c39cda30d) commit.

**Comment by FantasyWind2016** [comment]
Thanks,the code is right now.
