### ISSUE TITLE
Multi-level pie chart

### ISSUE THREAD

**Issue by RajIET** [sakrist/VBPieChart#37]
How to draw multi-level pie charts iOS. @ReDetection @sakrist @danydev 
![27023544-97b12cd2-4f70-11e7-9e57-9f267b74ace1](https://user-images.githubusercontent.com/13015133/27066765-0bb2b78c-5024-11e7-8398-e554eb175fd0.png)

**Comment by ReDetection** [comment]
Why did you mentioned me?

**Comment by RajIET** [comment]
@ReDetection  as per shown in suggestion

**Comment by ReDetection** [comment]
which suggestion?

**Comment by ReDetection** [comment]
So you're going to mention every person contributed to the project? I would highly discourage that. "Hey, you've been eating at this restaurant, and we have now our air condition broken, please look". 
No sense at all.

**Comment by sakrist** [comment]
I think this is something you can discover yourself. This is possible if you use 2 charts.
And, please, never add other developers to conversation without their permission.
