### ISSUE TITLE
How to custom selected pie at any index?

### ISSUE THREAD

**Issue by sonbui-savvycom** [sakrist/VBPieChart#7]
Thanks for your great chart!
Now, I want to set a selected pie like the attached image.
How can I do this?
Thanks in advance!.
![screen shot 2015-01-29 at 11 17 49 am](https://cloud.githubusercontent.com/assets/8241374/5952400/e2b85c5e-a7a8-11e4-9918-a5a73e7c8d67.png)

**Comment by sakrist** [comment]
You need change `innerRadius` and `outerRadius`. I have not checked it, but maybe will be enough.

**Comment by sonbui-savvycom** [comment]
Thanks @sakrist .
I helped me!
