### ISSUE TITLE
Is it possible to make the segments have different length?

### ISSUE THREAD

**Issue by Vivanda** [sakrist/VBPieChart#8]
Hi there, I wonder if it would be possible to draw the segments each with a different length. So it comes spike outside rather than being the same radius. Your animation actually already does it, so I guess it just would have to be adopted a bit?

**Comment by sakrist** [comment]
Yes. 
Take a look on `_angle`  and `_startAngle` in VBPiePiece.m.
With ```- (void) __angle:(float)angle``` you can change angle.

**Comment by Vivanda** [comment]
Sorry but I'm struggling with something simple. Would you mind helping me to phrase this in Swift. I would very much appreciate it. Thx

@property (nonatomic, retain) VBPieChart *chart;
@property (nonatomic, retain) NSArray *chartValues;

    self.chartValues = @[
                         @{@"name":@"first", @"value":@50, @"color":[UIColor colorWithHex:0xdd191daa]},
                         @{@"name":@"second", @"value":@20, @"color":[UIColor colorWithHex:0xd81b60aa]},
                         @{@"name":@"third", @"value":@40, @"color":[UIColor colorWithHex:0x8e24aaaa]},
                         @{@"name":@"fourth 2", @"value":@70, @"color":[UIColor colorWithHex:0x3f51b5aa]},
                         @{@"name":@"fourth 3", @"value":@65, @"color":[UIColor colorWithHex:0x5677fcaa]},
                         @{@"name":@"fourth 4", @"value":@23, @"color":[UIColor colorWithHex:0x2baf2baa]},
                         @{@"name":@"fourth 5", @"value":@34, @"color":[UIColor colorWithHex:0xb0bec5aa]},
                         @{@"name":@"fourth 6", @"value":@54, @"color":[UIColor colorWithHex:0xf57c00aa]}
                         ];

**Comment by sakrist** [comment]
I've made an example on swift. Check latest commit.
