### ISSUE TITLE
StartAngle Change causes slice to go out in Wrong directions.

### ISSUE THREAD

**Issue by sundeepsaluja5** [sakrist/VBPieChart#9]
Hi,

Thanks for the updated version. Everything is working fine in the latest version except when we change the start angle property from ZERO to some other value. The slices of pie chart comes out in wrong direction on selection.Any suggestion how can I fix this?

Thanks

**Comment by sakrist** [comment]
Something wrong with `_accentVector` in:
`- (void) pieceAngle:(float)angle start:(float)startAngle `

Try find code like below and uncomment, and see where red dots was created, that will help you with debugging.
```
#if DEBUG
//        CALayer *layer = [CALayer layer];
//        [layer setFrame:CGRectMake(center.x+_accentVector.x*size.width/2, center.y+_accentVector.y*size.height/2, 2, 2)];
//        layer.backgroundColor = [UIColor redColor].CGColor;
//        [self addSublayer:layer];
#endif
```

**Comment by sakrist** [comment]
Fixed
